### ISSUE TITLE
Error response from daemon: could not select device driver "" with capabilities: [[gpu]]

### ISSUE THREAD

**Issue by sreejith-mohanan** [ximinng/SVGDreamer#4]
Getting the following error while trying to run via docker

docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container:

**Comment by ximinng** [comment]
Can you provide more detailed error information?

**Comment by CodeGeek04** [comment]
i also got a bunch of errors while running in docker. i found the solution as follows-
from creator side-
- try building docker image without setting runtime as nvidia

what i did-
- run docker image without gpu
- deleted the files libnvidia.so.1 livcuda.so.1 and libcudadebugger.so.1
- docker commit to make new image

this new image runs without errors

**Comment by ximinng** [comment]
First of all, thank you for your advice~
I started with the official pytorch image to build the svgrender image, and the code must need nvidia to run, otherwise I am not sure if the code will run.
Did it work, according to you?

**Comment by CodeGeek04** [comment]
> First of all, thank you for your advice~
> I started with the official pytorch image to build the svgrender image, and the code must need nvidia to run, otherwise I am not sure if the code will run.
> Did it work, according to you?

Yeh it was working fine after deleting the mentioned files, but I dont know why those files were causing issues. I am working on Ubuntu latest jammu release, wsl
